### ISSUE TITLE
deploying a remix app without `@remix-run/vercel` installs an outdated version of remix

### ISSUE THREAD

**Issue by mcansh** [zeit/now#9010] opened 2022-12-05 21:17 UTC
deploying a remix app without explicitly having the `@remix-run/vercel` package installed will cause an older version (1.6.1) to be installed. instead can we detect the `@remix-run/dev` version being used and use that instead?

https://github.com/remix-run/remix/issues/4759

**Comment by franklinjavier** [comment] 2023-11-02 16:21
@vercel-team Any news about this issue?

**Comment by mcansh** [comment] 2023-11-02 16:32
> @vercel-team Any news about this issue?

should’ve been fixed in february https://github.com/vercel/vercel/pull/9375

**Comment by franklinjavier** [comment] 2023-11-02 16:38
Not yet 

![image](https://github.com/vercel/vercel/assets/440220/872bbd6c-3b48-4e78-b9a9-1a9393f244d0)

**Comment by TooTallNate** [comment] 2023-11-02 19:21
If you have a reproduction I can check it out.

However, I suggest using our Vercel template (`vercel init remix`), which already does not use `@remix-run/vercel`. In fact, that package is deprecated and you should be using `@vercel/remix` instead.

**Comment by franklinjavier** [comment] 2023-11-02 19:27
Hi @TooTallNate, thank you for the reply

I don't have a reproduction, because the repo is private. I'm giving up on updating. I managed to get it working with a workaround, but I feel it's not solid enough

```
- add serverModuleFormat: 'cjs', to remix.config.js
- remove "type": "module" from package.json
- install “@remix-run/vercel": "^1.19.3", -- This is essential to be able to work :( without this, the error above in the screenshot statement occurs
```

--- 

package.json

```json
{
  "name": "repo-name",
  "private": true,
  "sideEffects": false,
  "scripts": {
    "build": "remix build",
    "dev": "remix dev --manual",
    "start": "remix-serve ./build/index.js",
    "lint": "eslint --cache --ignore-path .gitignore . --ext ts,tsx",
    "lint:fix": "eslint --cache --ignore-path .gitignore --fix . --ext ts,tsx",
    "lint:ci": "eslint --ignore-path .gitignore . --ext ts,tsx",
    "format": "prettier --write \"**/*.{ts,tsx,md}\"",
    "clean": "rm -rf node_modules yarn.lock",
    "type-check": "tsc",
    "updatedeps": "yarn --latest upgrade-interactive",
    "prisma:update": "npx prisma db pull && npx prisma generate",
    "test": "yarn lint:ci && npx jest --forceExit --no-cache",
    "test:dev": "jest --watch",
    "postinstall": "npx prisma generate"
  },
  "dependencies": {
    "@radix-ui/react-dialog": "1.0.5",
    "@radix-ui/react-popover": "1.0.7",
    "@radix-ui/react-slider": "1.1.2",
    "@radix-ui/react-slot": "1.0.2",
    "@radix-ui/react-switch": "1.0.3",
    "@radix-ui/react-tooltip": "1.0.7",
    "@remix-run/vercel": "1.19.3",
    "@remix-run/node": "2.2.0",
    "@remix-run/react": "2.2.0",
    "@remix-run/serve": "2.2.0",
    "@tailwindcss/forms": "0.5.6",
    "@tanstack/react-table": "8.10.7",
    "@vercel/remix": "2.2.0",
    "axios": "1.6.0",
    "chart.js": "4.4.0",
    "clsx": "2.0.0",
    "cmdk": "0.2.0",
    "date-fns": "2.30.0",
    "dayjs": "1.11.10",
    "isbot": "3.7.0",
    "jsonwebtoken": "9.0.2",
    "logrocket": "6.0.1",
    "logrocket-react": "6.0.1",
    "lucide-react": "0.291.0",
    "nprogress": "0.2.0",
    "react": "18.2.0",
    "react-chartjs-2": "5.2.0",
    "react-day-picker": "8.9.1",
    "react-dom": "18.2.0",
    "react-number-format": "5.3.1",
    "remix-auth": "3.6.0",
    "remix-auth-auth0": "1.9.0",
    "uuid": "9.0.1",
    "yup": "1.3.2"
  },
  "devDependencies": {
    "@prisma/client": "5.5.2",
    "@remix-run/dev": "2.2.0",
    "@remix-run/eslint-config": "2.2.0",
    "@testing-library/jest-dom": "6.1.4",
    "@testing-library/react": "14.0.0",
    "@testing-library/user-event": "14.5.1",
    "@types/jest": "29.5.7",
    "@types/jest-axe": "3.5.7",
    "@types/jsonwebtoken": "9.0.4",
    "@types/logrocket-react": "3.0.2",
    "@types/nprogress": "0.2.2",
    "@types/react": "18.2.34",
    "@types/react-dom": "18.2.14",
    "@types/uuid": "9.0.6",
    "eslint": "8.52.0",
    "eslint-config-prettier": "9.0.0",
    "eslint-plugin-import": "2.29.0",
    "jest": "29.7.0",
    "jest-axe": "8.0.0",
    "jest-environment-jsdom": "29.7.0",
    "prettier": "3.0.3",
    "prettier-plugin-tailwindcss": "0.5.6",
    "prisma": "5.5.2",
    "rimraf": "5.0.5",
    "tailwind-merge": "2.0.0",
    "tailwindcss": "3.3.5",
    "tailwindcss-animate": "1.0.7",
    "ts-jest": "29.1.1",
    "typescript": "5.2.2"
  },
  "engines": {
    "node": ">=18.0.0"
  }
}
```

tsconfig.json

```ts
{
  "include": ["env.d.ts", "**/*.ts", "**/*.tsx"],
  "compilerOptions": {
    "lib": ["DOM", "DOM.Iterable", "ES2022"],
    "isolatedModules": true,
    "esModuleInterop": true,
    "jsx": "react-jsx",
    "moduleResolution": "Node",
    "resolveJsonModule": true,
    "target": "ES2022",
    "strict": true,
    "allowJs": true,
    "forceConsistentCasingInFileNames": true,
    "baseUrl": ".",
    "paths": {
      "~/*": ["./app/*"]
    },

    // Remix takes care of building everything in `remix build`.
    "noEmit": true
  }
}
```

remix.config.cjs

```cjs
/** @type {import('@remix-run/dev').AppConfig} */
module.exports = {
  ignoredRouteFiles: ['**/.*'],
  serverModuleFormat: 'cjs',
}
```

**Comment by franklinjavier** [comment] 2023-11-02 20:18
I imported the same repository on Vercel to create a new deploy from scratch. Same branch, the old one still gives an error and the new one worked 🤷‍♂️

![image](https://github.com/vercel/vercel/assets/440220/d945bde5-14aa-4125-8da1-88ee4e809d7c)

Do you have any ideas?

**Comment by TooTallNate** [comment] 2023-11-02 21:09
Take a look at the version of Vercel CLI that is being used in the build logs. I have a feeling you are pinning to an older version by setting the `VERCEL_CLI_VERSION` env var. You could also share deployment URLs (of the working vs. not working) with me and I could help take a closer look.

**Comment by TooTallNate** [comment] 2023-11-02 22:04
We got Frank's build issue sorted out via DM. I'll close this issue since the originally reported issue has been fixed since a while ago.

**Closed as completed by TooTallNate** 2023-11-02 22:04 UTC

**Comment by franklinjavier** [comment] 2023-11-02 22:39
@TooTallNate you saved the day, thank you! I removed the env var and worked it like a charm. 

Now I'm having another issue with LogRocket, as soon I figured out, I update this thread.

edit: downgraded the logrocket-react to 5.0.1 and it worked.
