### ISSUE TITLE
Can't install vercel with npm

### ISSUE THREAD

**Issue by Bereky** [zeit/now#8871] opened 2022-11-08 11:20 UTC
I was trying to install vercel to deploy my application using ``` npm install -g vercel ``` . 
But I'm getting an error like this:

``` 
npm ERR! code ETARGET
npm ERR! notarget No matching version found for @types/node@14.18.33. 
npm ERR! notarget a package version that doesn't exist.
```

Can you help me?

**Comment by andymckay** [comment] 2022-11-08 17:19
Thanks for the report. Could this have been an intermittent error? I am an unable to reproduce it locally and that version is available on npmjs as a public package: https://www.npmjs.com/package/@types/node/v/14.18.33

**Comment by Bereky** [comment] 2022-11-09 04:48
Thanks for the response. Yes, I am also unable to install the same npmjs package and still getting the same error. I have updated my node version to the latest about a week ago. Is this related in any way?

**Comment by nickspaargaren** [comment] 2022-11-12 10:10
I can't reproduce this as well using a new node Docker image.

> Thanks for the response. Yes, I am also unable to install the same npmjs package and still getting the same error. I have updated my node version to the **latest** about a week ago. Is this related in any way?

Whats your 'latest' node version currently? Try: `node --version`

You could try to see if there's other packages causing this: `npm -g outdated`

**Comment by Bereky** [comment] 2022-11-13 17:39
> Whats your 'latest' node version currently? Try: `node --version`

My current node version: ``` v18.12.1 ```

> You could try to see if there's other packages causing this: `npm -g outdated`

Current npm version on my machine: ``` 8.1.4 ```, where the latest is ``` 9.1.1``` 
This might be the issue. I'll have to upgrade npm and see if it's fixed. Thanks.

**Comment by andymckay** [comment] 2022-11-21 19:43
Any luck @Bereky? I suspect this is not a problem on `vercel/vercel` side of things, but somewhere in your node, npm stack, so I'm going to close this issue.

**Closed as completed by andymckay** 2022-11-21 19:43 UTC
