### ISSUE TITLE
Error: Cannot find module 'path-to-regexp'

### ISSUE THREAD

**Issue by dstaley** [zeit/now#9735] opened 2023-03-30 03:33 UTC
Looks like `@vercel/node` depends on `path-to-regexp` at runtime, but that dependency is [specified as a dev dependency](https://github.com/vercel/vercel/blob/main/packages/node/package.json#L62) for `@vercel/node`.

```
Require stack:
- C:\app\node_modules\@vercel\node\dist\utils.js     
- C:\app\node_modules\@vercel\node\dist\dev-server.js
    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:1075:15)
    at Function.Module._resolveFilename.sharedData.moduleResolveFilenameHook.installedValue [as _resolveFilename] (C:\app\node_modules\@cspotcode\source-map-support\source-map-support.js:811:30)
    at Function.Module._load (node:internal/modules/cjs/loader:920:27)
    at Module.require (node:internal/modules/cjs/loader:1141:19)
    at require (node:internal/modules/cjs/helpers:110:18)
    at Object.<anonymous> (C:\app\node_modules\@vercel\node\dist\utils.js:5:26)
    at Module._compile (node:internal/modules/cjs/loader:1254:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1308:10)
    at Object.require.extensions.<computed> [as .js] (C:\app\node_modules\ts-node\src\index.ts:1608:43)
    at Module.load (node:internal/modules/cjs/loader:1117:32) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    'C:\\app\\node_modules\\@vercel\\node\\dist\\utils.js',
    'C:\\app\\node_modules\\@vercel\\node\\dist\\dev-server.js'
  ]
}
```

**Comment by D-260** [comment] 2023-04-02 16:53
Hey, I just analysed this problem a bit and I went through the history of the commits since the one you mentioned. 
This is pretty confusing to me as I am not able to follow the trail of this module as well.

**Comment by EndangeredMassa** [comment] 2023-04-03 15:41
@dstaley hello!

It looks like you ran `vc dev` on a Windows machine for a project using middleware. I tried to reproduce this issue on `vercel@latest`, but it worked fine for me.

Can you provide some more details about what you were doing when you saw this error? A reproduction repo would be super helpful, too.

**Comment by dstaley** [comment] 2023-04-06 00:32
@EndangeredMassa Hi! That's correct, this is on Windows and uses an API route.

I can totally give you a `package-lock.json` that reproduces the `node_modules` layout that causes this, but I think it's pretty clear from the code that `@vercel/node` does not correctly declare its dependency on `path-to-regexp`. The specific situation that got me here is that I had `react-scripts` installed in my project _before_ I installed `vercel` as a dev dependency. This meant that the version of `path-to-regexp` hoisted to `node_modules/path-to-regexp` was outside of the semver range declared by one of `vercel`'s dependencies. This meant that the correct version of `path-to-regexp` was stored deeper in the package tree. When I uninstalled `react-scripts`, npm removed the top-level `path-to-regexp` (since it was no longer needed). This resulted in the error above.

If having the actual `package-lock.json` (and a fully-reproducing example) would be helpful just let me know and I can upload that! I just figure it's pretty clear that `@vercel/node` should have `path-to-regexp` in its dependencies.

Also, just in case it's important: I'm installing `vercel` as a local dev dependency instead of a gloabl dependency. I figure that's a supported use-case, but if not please let me know as well!

**Comment by dan-stowell** [comment] 2023-04-12 19:26
Thanks for the detailed response, @dstaley ! (And for pulling on the `path-to-regexp` thread.) Having the actual `package-lock.json` and a repro would be most excellent.

I'm digging into whether installing `vercel` as a dev dependency is supported and whether `path-to-regexp` should be declared as a dev dependency or dependency in `@vercel/node`.

**Comment by cb1kenobi** [comment] 2023-04-17 16:06
After doing some testing, I wasn't able to reproduce the issue, but I discovered that it's probably because `@vercel/remix-builder` and `@vercel/routing-utils` were hoisting `path-to-regexp`. I discovered that `ts-morph` is also susceptible to this issue. I've created a PR to reassign the `@vercel/node` dependencies: https://github.com/vercel/vercel/pull/9823.

**Comment by cb1kenobi** [comment] 2023-04-17 18:37
@dstaley If you have a moment, would you mind testing the Vercel CLI build for #9823? You should be able to update it in your `package.json`:

```
"vercel": "https://vercel-hcaxn3u5i.vercel.sh/tarballs/vercel.tgz"
```

**Comment by dstaley** [comment] 2023-04-18 00:44
@cb1kenobi works like a charm! And the output of `npm ls path-to-regexp` indicates that `@vercel/node` has access to its own copy of `path-to-regexp` as expected.

```
$ npm ls path-to-regexp
`-- vercel@28.18.5-be759a8
  +-- @vercel/node@2.10.3-be759a8
  | `-- path-to-regexp@6.2.1
  +-- @vercel/redwood@1.1.14-be759a8
  | `-- @vercel/routing-utils@2.2.0-be759a8
  |   `-- path-to-regexp@6.1.0
  `-- @vercel/remix-builder@1.8.4-be759a8
    `-- path-to-regexp@6.2.1
```

Compared to before:
```
$ npm ls path-to-regexp
`-- vercel@28.18.5
  +-- @vercel/redwood@1.1.14
  | `-- @vercel/routing-utils@2.2.0
  |   `-- path-to-regexp@6.1.0
  `-- @vercel/remix-builder@1.8.4
    `-- path-to-regexp@6.2.1
```

**Comment by cb1kenobi** [comment] 2023-04-18 01:53
Awesome, huge thanks for helping test!

**Closed as completed** 2023-04-18 16:37 UTC
